
# port
server:
    port: 8088

# evn
spring:
  application:
    name: aurora_gradle
  profiles:
    active: dev

# mybatis
mybatis:
  type-aliases-package: cn.aurora.dao               # 别名
  mapper-locations: classpath*:mapper/*.xml         # 等同于@mapper
  configuration:
    map-underscore-to-camel-case: true              # 驼峰

# mybatis-mapper
mapper:
  mappers: tk.mybatis.mapper.common.Mapper
  not-empty: false
  identity: mysql

# sql-log
logging:
  level:
    com.free.zero.server: debug